# Generated by Django 4.2 on 2023-05-29 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_producte_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atribute',
            name='products',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AddField(
            model_name='atribute',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_atrib', to='product.producte'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='product.producte', verbose_name='Продукт'),
        ),
    ]
