# Generated by Django 4.2 on 2023-04-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_producte_delete_product_atribute_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atribute',
            options={'verbose_name': 'Атрибут', 'verbose_name_plural': 'Атрибуты'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='producte',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='atribute',
            name='product',
        ),
    ]
