# Generated by Django 4.2 on 2023-05-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_atribute_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producte',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='Категория продукта'),
        ),
    ]
