# Generated by Django 4.2 on 2023-04-24 20:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producte',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
