# Generated by Django 4.2 on 2023-05-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_atribute_product_alter_photo_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atribute',
            name='value',
            field=models.CharField(max_length=200, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('ОТ', 'Отмененный'), ('АК', 'Активный'), ('ЗП', 'Запрошено'), ('ПЛ', 'Получено')], default='null', max_length=10, null=True, verbose_name='Статус заказа'),
        ),
    ]
