# Generated by Django 4.2 on 2023-04-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_producte_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atribute',
            old_name='tags',
            new_name='products',
        ),
    ]
