# Generated by Django 4.2 on 2023-05-07 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_atribute_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producte')),
            ],
            options={
                'verbose_name': 'Фото продукта',
                'verbose_name_plural': 'фотограффии продукта',
            },
        ),
    ]
