# Generated by Django 4.2 on 2023-05-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('ОТ', 'Отмененный'), ('АК', 'Активный'), ('ЗП', 'Запрошено'), ('ПЛ', 'Получено')], default='null', max_length=2, null=True),
        ),
    ]
