# Generated by Django 4.2 on 2023-05-23 17:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_atribute_title_alter_atribute_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producte',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='описание Категории'),
        ),
        migrations.AlterField(
            model_name='producte',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='содержание продукта'),
        ),
        migrations.AlterField(
            model_name='producte',
            name='description',
            field=models.CharField(max_length=150, verbose_name='описание Продукта'),
        ),
    ]
