# Generated by Django 4.2 on 2023-05-26 14:56

import ckeditor_uploader.fields
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='producte',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='media/images/', verbose_name='Фото продукта'),
        ),
        migrations.AlterField(
            model_name='producte',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='содержание продукта'),
        ),
    ]
